### PR TITLE
Fix testSpamStrings function

### PR DESCRIPTION
**Pull request by GaryStanton**
This function wasn't actually checking against the spam strings and would always return a pass condition.

### CODE REVIEW

**Comment by tonyjunkes** [comment]
Thanks for the contribution. I will review this soon.

**Comment by tonyjunkes** [comment]
@GaryStanton, can you provide a scenario where the function does not properly check against the spam strings so that I may test further?

I did a quick test against the default blacklisted items and everything appeared to validate as expected.

```
CFFPVerify = createObject( "component", "cfformprotect.CFFPVerify" ).init();
writeDump( CFFPVerify.testSpamStrings( { testField: "free music" } ) );
```

**Comment by GaryStanton** [comment]
@tonyjunkes Have you tried when your test field contains more than just the words 'free music'? Something like 'download free music now from this website'? ArrayFind requires an exact match between the field and the array value, so if the field contains more text as it usually would in the wild, it'll pass every time.

**Comment by tonyjunkes** [comment]
Ah, very true. Thanks for clarifying. I think I only ever implemented this in a live app once and even then, it moved on to other approaches, so I never tested everything completely.

**Comment by GaryStanton** [comment]
It's easy to miss - I've been using CFFormProtect for _years_ and never noticed it either!
Thanks for merging.

**Pull request merged**
